### ISSUE TITLE
No module named webkit

### ISSUE THREAD

**Issue by lakshmi999** [rwl/muntjac#22]
i have run muntjac on command line its working but i have to run example.py file with the following code,

from muntjac.api import Application, Label, Window
from muntjac.terminal.gwt.server.application_servlet import ApplicationServlet
from paste.session import SessionMiddleware

 class HelloWorld(Application):
    def init(self):
            main = Window('Hello window')
        self.setMainWindow(main)
        main.addComponent(Label('Hello World!'))

wsgi_app = ApplicationServlet(HelloWorld, debug=True)

wsgi_app = SessionMiddleware(wsgi_app)

httpd = make_server('localhost', 8080, wsgi_app)
httpd.serve_forever()

Traceback (most recent call last):
  File "pythonwithvaadin.py", line 4, in <module>
    from muntjac.api import Application, Label, Window
  File "/usr/lib/python2.7/site-packages/Muntjac-1.1.2-py2.7.egg/muntjac/api.py", line 17, in <module>
    from muntjac.application import Application
  File "/usr/lib/python2.7/site-packages/Muntjac-1.1.2-py2.7.egg/muntjac/application.py", line 24, in <module>
    from muntjac.util import EventObject, IEventListener, defaultLocale
  File "/usr/lib/python2.7/site-packages/Muntjac-1.1.2-py2.7.egg/muntjac/util.py", line 21, in <module>
    import paste.webkit
ImportError: No module named webkit

**Comment by lakshmi999** [comment]
pls rply me

**Comment by lakshmi999** [comment]
solved my error,i have put the example.py file aside the muntjac package and run,its working fine.
